/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion.PatronoVentana;

import LogicaNegocio.LogicaEmpleados;
import Servicios.ServicioEmpleado;
import Entidades.Nominas;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import Entidades.Empleados;
import LogicaNegocio.LogicaNominas;
import Servicios.ServicioPatrono;
import com.itextpdf.text.DocumentException;
import Presentacion.VentanaLogin;
import javax.mail.MessagingException;
import javax.mail.SendFailedException;

/**
 *
 * @author Empresaurio50
 */

public class VentanaPatrono extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPatrono
     */
    private ServicioEmpleado servicioEmpleado;
    private Nominas objNominas;
    private Empleados objEmpleados;
    private VentanaPlantilla ventanaCRUD;
    private VentanaCorreo ventanaCorreo;
    private ServicioPatrono servicioPatrono;
    private VentanaLogin ventanaLogin;

    public VentanaPatrono() {
        try {

            servicioPatrono = new LogicaNominas();
            servicioEmpleado = new LogicaEmpleados();
        } catch (IOException e) {
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bttPlantilla = new javax.swing.JButton();
        bttReporteNomina = new javax.swing.JButton();
        bttReportes = new javax.swing.JButton();
        bttAtras = new javax.swing.JButton();
        lblOpciones = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttPlantilla.setBackground(new java.awt.Color(250, 250, 250));
        bttPlantilla.setText("Planilla");
        bttPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttPlantillaActionPerformed(evt);
            }
        });
        jPanel1.add(bttPlantilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 140, 40));

        bttReporteNomina.setBackground(new java.awt.Color(252, 252, 252));
        bttReporteNomina.setText("Reporte Nomina");
        bttReporteNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttReporteNominaActionPerformed(evt);
            }
        });
        jPanel1.add(bttReporteNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 140, 40));

        bttReportes.setBackground(new java.awt.Color(252, 252, 252));
        bttReportes.setText("Reportes Empleados");
        bttReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttReportesActionPerformed(evt);
            }
        });
        jPanel1.add(bttReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 180, 40));

        bttAtras.setBackground(new java.awt.Color(252, 252, 252));
        bttAtras.setText("Cerrar Session");
        bttAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(bttAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 160, 60));

        lblOpciones.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        lblOpciones.setText("Menu");
        jPanel1.add(lblOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prueba 2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondaxo de todo lado.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, -70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttPlantillaActionPerformed

        try {
            ventanaCRUD = new VentanaPlantilla();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        ventanaCRUD.setVisible(true);
        ventanaCRUD.setLocationRelativeTo(null);
        this.setVisible(false);

    }//GEN-LAST:event_bttPlantillaActionPerformed

    private void bttReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttReportesActionPerformed

        ventanaCorreo = new VentanaCorreo();

        ventanaCorreo.setVisible(true);
        ventanaCorreo.setLocationRelativeTo(null);
        this.setVisible(false);


    }//GEN-LAST:event_bttReportesActionPerformed

    /** 
     * Acción a realizar cuando se pulsa el botón de reporte de nómina. 
     * Este método se encarga de calcular el total a pagar de las nóminas, 
     * generar un archivo PDF con el reporte de nómina y manejar posibles 
     * excepciones que ocurran durante el proceso. 
     * @param evt El evento de acción que disparó este método. 
     */
    private void bttReporteNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttReporteNominaActionPerformed

        objNominas = new Nominas();
        objEmpleados = new Empleados();

        try {
            servicioEmpleado.leerEmpleado(objEmpleados);

            double totalPagar = 0;
            // Calcula el total a pagar sumando los salarios brutos de todos los empleados.
            for (String[] datosPatrono : objEmpleados.getEmpleadosLista()) {

                totalPagar = totalPagar + Double.parseDouble(datosPatrono[4]);

            }
            objNominas.setTotalPagar(totalPagar);// Establece el total a pagar en el objeto Nominas.

            
            servicioPatrono.crearPDF(objNominas);
            servicioPatrono.enviarCorreoPatrono(objNominas);
            JOptionPane.showMessageDialog(null, "Se le envio un PDF a su correo");
            

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "El archivo ya esta creado");
        } catch (DocumentException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (SendFailedException ex) {
            Logger.getLogger(VentanaPatrono.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MessagingException ex) {
            Logger.getLogger(VentanaPatrono.class.getName()).log(Level.SEVERE, null, ex);
        }
 

    }//GEN-LAST:event_bttReporteNominaActionPerformed

    private void bttAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAtrasActionPerformed
        
        ventanaLogin = new VentanaLogin();
        
        ventanaLogin.setVisible(true);
        ventanaLogin.setLocationRelativeTo(null);
        
        this.setVisible(false);
        
    }//GEN-LAST:event_bttAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(VentanaPatrono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(VentanaPatrono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(VentanaPatrono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(VentanaPatrono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new VentanaPatrono().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAtras;
    private javax.swing.JButton bttPlantilla;
    private javax.swing.JButton bttReporteNomina;
    private javax.swing.JButton bttReportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblOpciones;
    // End of variables declaration//GEN-END:variables
}
